export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL= 'HIDE_SIGNUP_MODAL';
export const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL';
export const HIDE_SIGNIN_MODAL= 'HIDE_SIGNIN_MODAL';
