export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL= 'HIDE_SIGNUP_MODAL';
export const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL';
export const HIDE_SIGNIN_MODAL= 'HIDE_SIGNIN_MODAL';
export const SHOW_PROFILE_MODAL = 'SHOW_PROFILE_MODAL';
export const HIDE_PROFILE_MODAL= 'HIDE_PROFILE_MODAL';
export const SHOW_CART_MODAL = 'SHOW_CART_MODAL';
export const HIDE_CART_MODAL = 'HIDE_CART_MODAL';